from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    Image,
    Table,
    TableStyle
)

from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.enums import TA_CENTER
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib import colors
from engine.interpretation import generate_planet_section
from engine.interpretation import SYSTEM_NAMES

import os
import datetime

BLACK = HexColor("#000000")
GOLD = HexColor("#FFBF00")
LIGHT_TEXT = HexColor("#F1E5AC")

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

body_style = ParagraphStyle(
    "BodyStyle",
    fontName="BodyFont",
    fontSize=12,
    leading=20,
    textColor=LIGHT_TEXT,
    alignment=0,  # left aligned
    spaceAfter=10
)
# -----------------------------
# FONTS
# -----------------------------

pdfmetrics.registerFont(
    TTFont(
        "TitleFont",
        os.path.join(BASE_DIR, "fonts", "PlayfairDisplay-VariableFont_wght.ttf")
    )
)

pdfmetrics.registerFont(
    TTFont(
        "BodyFont",
        os.path.join(BASE_DIR, "fonts", "LibreBaskerville-VariableFont_wght.ttf")
    )
)

divider = ParagraphStyle(
    "Divider",
    fontName="TitleFont",
    fontSize=16,
    textColor=GOLD,
    alignment=1,  # center
    spaceBefore=20,
    spaceAfter=20
)

# -----------------------------
# PAGE DECOR
# -----------------------------

def page_decor(canvas, doc):

    width, height = LETTER

    # background
    canvas.setFillColor(BLACK)
    canvas.rect(0, 0, width, height, fill=1, stroke=0)

    # gold border
    canvas.setStrokeColor(GOLD)
    canvas.setLineWidth(1)
    canvas.rect(30, 30, width - 60, height - 60)

    # watermark logo for pages after cover
    if doc.page > 1:

        logo_path = os.path.join(BASE_DIR, "assets", "ametra_logo.png")

        if os.path.exists(logo_path):

            canvas.saveState()

            canvas.setFillAlpha(0.05)

            canvas.drawImage(
                logo_path,
                width / 2 - 170,
                height / 2 - 170,
                width=340,
                height=340,
                mask="auto"
            )

            canvas.restoreState()

    canvas.setFont("BodyFont", 9)
    canvas.setFillColor(LIGHT_TEXT)

    canvas.drawCentredString(width / 2, 35, "Generated by Ametra")


# -----------------------------
# ASTROLOGY TABLE
# -----------------------------

def build_chart_table(chart_data):

    table_data = [["Planet", "Sign", "House", "Degree", "Retrograde"]]

    for planet, data in chart_data["D1"].items():

        table_data.append([
            planet,
            data["sign"],
            data.get("house", "-"),
            f"{round(data['degree'], 2)}°",
            "Yes" if data["retrograde"] else "No"
        ])

    table = Table(
        table_data,
        colWidths=[90, 90, 80, 90, 100]
    )

    table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), GOLD),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),

        ("TEXTCOLOR", (0, 1), (-1, -1), LIGHT_TEXT),

        ("ALIGN", (0, 0), (-1, -1), "CENTER"),

        ("FONTNAME", (0, 0), (-1, 0), "TitleFont"),
        ("FONTNAME", (0, 1), (-1, -1), "BodyFont"),

        ("GRID", (0, 0), (-1, -1), 0.5, GOLD)

    ]))

    return table

def extract_tarot(archetype):

    tarot = archetype.get("tarot")

    if isinstance(tarot, dict):
        return tarot.get("neutral", "Unknown")

    return tarot or "Unknown"
    
def build_intensity_table(pii_scores):

    systems = {
        "Sun": "Identity System",
        "Moon": "Emotional System",
        "Mercury": "Thinking & Communication System",
        "Venus": "Relationship Pattern",
        "Mars": "Action System",
        "Jupiter": "Expansion & Wisdom System",
        "Saturn": "Pressure & Karmic System",
        "Rahu": "Growth Drive",
        "Ketu": "Detachment Pattern"
    }

    def get_label(score):

        if score >= 6:
            return "Dominant"

        elif score >= 4:
            return "Strong"

        else:
            return "Present"

    table_data = [["Psychological System", "Intensity"]]

    for planet, system in systems.items():

        score = pii_scores.get(planet, 3)

        label = get_label(score)

        table_data.append([system, label])

    table = Table(
        table_data,
        colWidths=[260, 120]
    )

    table.setStyle(TableStyle([

        ("BACKGROUND", (0,0), (-1,0), GOLD),
        ("TEXTCOLOR", (0,0), (-1,0), colors.black),

        ("TEXTCOLOR", (0,1), (-1,-1), LIGHT_TEXT),

        ("ALIGN", (0,0), (-1,-1), "CENTER"),

        ("FONTNAME", (0,0), (-1,0), "TitleFont"),
        ("FONTNAME", (0,1), (-1,-1), "BodyFont"),

        ("GRID", (0,0), (-1,-1), 0.5, GOLD)

    ]))

    return table    
    
def build_profile_summary(archetypes, pii_scores):
    
    core = archetypes.get("core", {})
    growth = archetypes.get("growth", {})

    core_title = core.get("title", "Unknown")
    growth_title = growth.get("title", "Unknown")

    qualities = core.get("qualities", [])
    limitations = core.get("limitations", [])

    qualities_text = ", ".join(qualities[:4])
    limitations_text = ", ".join(limitations[:3])
    
    # determine dominant / strong systems from pii scores
    dominant_systems = []
    strong_systems = []

    for planet, score in pii_scores.items():

        system = SYSTEM_NAMES.get(planet, planet)

        if score >= 6:
            dominant_systems.append(system)

        elif score >= 4:
            strong_systems.append(system)
            
    dominant_text = "<br/>".join(dominant_systems)
    strong_text = "<br/>".join(strong_systems)        

    core = archetypes.get("core", {})
    growth = archetypes.get("growth", {})

    core_name = core.get("title", "Unknown")
    growth_name = growth.get("title", "Unknown")

    systems = {
        "Sun": "Identity System",
        "Moon": "Emotional System",
        "Mercury": "Thinking & Communication System",
        "Venus": "Relationship Pattern",
        "Mars": "Action System",
        "Jupiter": "Expansion & Wisdom System",
        "Saturn": "Pressure & Karmic System",
        "Rahu": "Growth Drive",
        "Ketu": "Detachment Pattern"
    }

    dominant = []
    strong = []

    for planet, score in pii_scores.items():

        name = systems.get(planet, planet)

        if score >= 6:
            dominant.append(name)

        elif score >= 4:
            strong.append(name)

    dominant_text = ", ".join(dominant) if dominant else "None"
    strong_text = ", ".join(strong) if strong else "None"

    qualities = core.get("qualities", [])
    limitations = core.get("limitations", [])

    q_text = ", ".join(qualities[:4])
    l_text = ", ".join(limitations[:3])
    
    table_data = [

    ["Core Archetype", Paragraph(core_title, body_style)],

    ["Growth Direction", Paragraph(growth_title, body_style)],

    ["Dominant Systems", Paragraph(dominant_text, body_style)],

    ["Strong Systems", Paragraph(strong_text, body_style)],

    ["Key Qualities", Paragraph(qualities_text, body_style)],

    ["Development Focus", Paragraph(limitations_text, body_style)]

    ]
        
    table = Table(table_data, colWidths=[200, 300])

    table.setStyle(TableStyle([

        ("BACKGROUND",(0,0),(0,-1),GOLD),
        ("TEXTCOLOR",(0,0),(0,-1),colors.black),

        ("TEXTCOLOR",(1,0),(1,-1),LIGHT_TEXT),

        ("FONTNAME",(0,0),(-1,-1),"BodyFont"),

        ("GRID",(0,0),(-1,-1),0.5,GOLD)

    ]))

    return table    
    
# -----------------------------
# PDF GENERATOR
# -----------------------------
def generate_pdf(chart_data, archetypes, pii_scores, user_name="User", preview=False):
    
    folder = os.path.join(BASE_DIR, "generated_pdf")
    os.makedirs(folder, exist_ok=True)

    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")

    file_path = os.path.join(
        folder,
        f"ametra_preview_{timestamp}.pdf" if preview else f"ametra_report_{timestamp}.pdf"
    )

    doc = SimpleDocTemplate(
        file_path,
        pagesize=LETTER,
        rightMargin=110,
        leftMargin=110,
        topMargin=90,
        bottomMargin=70
    )


    # -----------------------------
    # STYLES
    # -----------------------------

    cover_title = ParagraphStyle(
        "CoverTitle",
        fontName="TitleFont",
        fontSize=28,
        leading=36,
        textColor=LIGHT_TEXT,
        alignment=TA_CENTER,
        spaceAfter=18
    )

    cover_desc = ParagraphStyle(
        "CoverDesc",
        fontName="BodyFont",
        fontSize=12,
        leading=22,
        textColor=LIGHT_TEXT,
        alignment=TA_CENTER
    )

    section_title = ParagraphStyle(
        "SectionTitle",
        fontName="TitleFont",
        fontSize=22,
        leading=28,
        textColor=GOLD,
        alignment=TA_CENTER,
        spaceAfter=20
    )


    story = []


    # -----------------------------
    # PAGE 1 — COVER
    # -----------------------------

    story.append(Spacer(1, 90))

    logo_path = os.path.join(BASE_DIR, "assets", "ametra_logo.png")

    if os.path.exists(logo_path):

        story.append(Image(
            logo_path,
            width=240,
            height=240
        ))

    story.append(Spacer(1, 40))

    story.append(Paragraph(
        "A Psychological Map of Your Inner Systems",
        cover_title
    ))

    story.append(Paragraph(
        f"Prepared for <b>{user_name}</b>",
        cover_desc
    ))

    story.append(PageBreak())


    # -----------------------------
    # PAGE 2 — ASTROLOGY CONFIG
    # -----------------------------

    story.append(Paragraph(
        "ASTROLOGICAL CONFIGURATION",
        section_title
    ))

    story.append(Spacer(1, 20))

    story.append(build_chart_table(chart_data))

    story.append(Spacer(1, 20))

    dasha = chart_data.get("Dasha", {})

    story.append(Paragraph(
        f"Current Planetary Period — Mahadasha: {dasha.get('Mahadasha','Unknown')} | Antardasha: {dasha.get('Antardasha','Unknown')}",
        cover_desc
    ))
    
    story.append(Paragraph(
    
    """ *The Table and Dashas are calculated by vedic calculations.""",
    cover_desc ))
    # -----------------------------
    # PAGE 3 — CORE ARCHETYPE
    # -----------------------------

    core = archetypes.get("core", {})

    story.append(PageBreak())

    story.append(Paragraph(
        "CORE ARCHETYPE",
        section_title
    ))

    story.append(Spacer(1,20))

    story.append(Paragraph(
        core.get("title","Unknown").upper(),
        cover_title
    ))

    story.append(Spacer(1,20))

    story.append(Paragraph(
        "Archetype Overview",
        section_title
    ))

    story.append(Paragraph(
        core.get("description",""),
        cover_desc
    ))

    story.append(Spacer(1,10))

    story.append(Paragraph(
        "Psychological Meaning",
        section_title
    ))

    story.append(Paragraph(
        core.get("archetype_meaning",""),
        cover_desc
    ))

    story.append(Spacer(1,15))

    qualities = core.get("qualities", [])

    if qualities:

        q_text = "<br/>".join([f"• {q}" for q in qualities])

        story.append(Paragraph(
            "Qualities To Preserve",
            section_title
        ))

        story.append(Paragraph(
            q_text,
            cover_desc
        ))

    story.append(Spacer(1,15))

    limits = core.get("limitations", [])

    if limits:

        l_text = "<br/>".join([f"• {l}" for l in limits])

        story.append(Paragraph(
            "Common Limitations",
            section_title
        ))

        story.append(Paragraph(
            l_text,
            cover_desc
        ))

    story.append(Spacer(1,15))

    story.append(Paragraph(
        "Tarot Mirror",
        section_title
    ))

    story.append(Paragraph(
        extract_tarot(core).upper(),
        cover_title
    ))

    story.append(Paragraph(
        core.get("tarot_meaning",""),
        cover_desc
    ))


    # -----------------------------
    # PAGE 4 — GROWTH ARCHETYPE
    # -----------------------------

    growth = archetypes.get("growth", {})

    story.append(PageBreak())

    story.append(Paragraph(
        "GROWTH ARCHETYPE",
        section_title
    ))

    story.append(Spacer(1,20))

    story.append(Paragraph(
        growth.get("title","Unknown").upper(),
        cover_title
    ))

    story.append(Spacer(1,20))

    story.append(Paragraph(
        "Archetype Overview",
        section_title
    ))

    if preview:
        text = "<br/>".join(["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"] * 4)
    else:
        text = growth.get("description","")

    story.append(Paragraph(text, cover_desc))

    story.append(Spacer(1,10))

    story.append(Paragraph(
        "Psychological Meaning",
        section_title
    ))

    if preview:
        text = "<br/>".join(["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"] * 4)
    else:
        text = growth.get("archetype_meaning","")

    story.append(Paragraph(text, cover_desc))

    story.append(Spacer(1,15))

    qualities = growth.get("qualities", [])

    if qualities:

        story.append(Paragraph(
            "Qualities To Preserve",
            section_title
        ))

        if preview:
            q_text = "<br/>".join(["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"] * 3)
        else:
            q_text = "<br/>".join([f"• {q}" for q in qualities])

        story.append(Paragraph(
            q_text,
            cover_desc
        ))

    story.append(Spacer(1,15))

    limits = growth.get("limitations", [])

    if limits:

        story.append(Paragraph(
            "Common Limitations",
            section_title
        ))

        if preview:
            l_text = "<br/>".join(["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"] * 3)
        else:
            l_text = "<br/>".join([f"• {l}" for l in limits])

        story.append(Paragraph(
            l_text,
            cover_desc
        )) 

    story.append(Spacer(1,15))

    story.append(Paragraph(
        "Tarot Mirror",
        section_title
    ))

    story.append(Paragraph(
        extract_tarot(growth).upper(),
        cover_title
    ))

    if preview:
        text = "<br/>".join(["━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"] * 3)
    else:
        text = growth.get("tarot_meaning","")

    story.append(Paragraph(
        text,
        cover_desc
    ))

        
    # -----------------------------
    # PAGE 5 — SYSTEM INTENSITY
    # -----------------------------

    story.append(PageBreak())

    story.append(Paragraph(
        "PSYCHOLOGICAL SYSTEM INTENSITY",
        section_title
    ))

    story.append(Spacer(1,20))

    story.append(build_intensity_table(pii_scores))

    story.append(Spacer(1,25))

    story.append(Paragraph(
    
    """ Each psychological system in your chart operates with a different level of influence.""",
    cover_desc ))

    story.append(Spacer(1,20))

    story.append(Paragraph( 
    
    """Dominant systems tend to shape your natural reactions and behavior patterns most strongly.
     They are often the psychological processes that guide how you experience identity,
     emotion, or decision-making in everyday life.""",
     cover_desc ))
     
    story.append(Spacer(1,20))
    
    story.append(Paragraph( 
    
    """Strong systems remain highly active influences but may operate more flexibly depending
      on circumstances and personal awareness.""",
      cover_desc))
    
    story.append(Spacer(1,20))

    story.append(Paragraph( 
    
    """Present systems still contribute to your psychological structure, but they usually
      express themselves more subtly or in specific situations rather than constantly.""",
      cover_desc))
      
    story.append(Spacer(1,20))

    story.append(Paragraph( 

    """Understanding which systems are dominant or strong can help you recognize where your
       natural strengths appear and where conscious awareness may help create greater balance.""",
  
    cover_desc
    ))
    
        
    story.append(PageBreak())

    
    # -----------------------------
    # PAGE 6+ SYSTEM SECTIONS
    # -----------------------------

    planets = [
    "Sun",
    "Moon",
    "Mercury",
    "Venus",
    "Mars",
    "Jupiter",
    "Saturn",
    "Rahu",
    "Ketu"
    ]

    for p_index, planet in enumerate(planets):

        story.append(Spacer(1,30))

        section_text = generate_planet_section(
            planet,
            chart_data,
            pii_scores
        )

        lines = [l.strip() for l in section_text.split("\n") if l.strip()]

        story.append(Paragraph(
            lines[0],
            section_title
        ))

        for line in lines[1:]:

            if preview and p_index >= 2:
                story.append(Paragraph(
                    "───────────────",
                    body_style
                ))
            else:
                story.append(Paragraph(
                    line,
                    body_style
                ))

            story.append(Spacer(1,6))
    # -----------------------------
    # FINAL PAGE — USER PROFILE
    # -----------------------------

    story.append(PageBreak())

    story.append(Paragraph(
        "YOUR PSYCHOLOGICAL PROFILE SUMMARY",
        section_title
    ))

    story.append(Spacer(1,25))

    story.append(build_profile_summary(
        archetypes,
        pii_scores
    ))

    story.append(Spacer(1,30))

    story.append(Paragraph(
     
    "Each psychological system in your chart operates with a different level of influence.",
    body_style
     ))
    
    story.append(Spacer(1,20))

    
    story.append (Paragraph(
    
    "Dominant systems shape your natural reactions and behavioral patterns most strongly. These systems often guide how you experience identity, emotions, and decision-making in everyday life.",
    body_style
    ))

    story.append(Spacer(1,20))

    story.append(Paragraph(
    
    "Strong systems remain active influences but operate more flexibly depending on circumstances and awareness. Present systems still contribute to your psychological structure but usually appear in specific situations rather than constantly.",
    body_style ))
   
    
    
    # -----------------------------
    # FINAL PAGE — NOTE FROM AMETRA
    # -----------------------------

    story.append(PageBreak())

    story.append(Paragraph(
        "A NOTE FROM AMETRA",
        section_title
    ))

    story.append(Spacer(1,30))

    story.append(Paragraph(
    """
    Every person carries a unique combination of tendencies, strengths, and inner patterns.
    These patterns are not limits — they are starting points for awareness.

    The purpose of this report is not to define who you must be, but to help illuminate how
    your internal systems naturally operate. When these patterns become visible, you gain
    the ability to guide them more consciously rather than being guided by them unconsciously.
    """,
    body_style
    ))

    story.append(Spacer(1,20))

    story.append(Paragraph(
    """
    Some qualities described in this report may feel immediately familiar, while others may
    become clearer only through reflection and experience. Psychological growth rarely
    happens all at once — it unfolds gradually as awareness deepens.
    """,
    body_style
    ))

    story.append(Spacer(1,20))

    story.append(Paragraph(
    """
    At Ametra we believe that insight is most valuable when it supports understanding,
    compassion, and personal growth. The patterns described here are simply one way of
    observing the complex and evolving nature of the human mind.

    Where awareness grows, freedom grows with it.
    """,
    body_style
    ))

    story.append(Spacer(1,30))

    story.append(Paragraph("✦", divider))
        
    # -----------------------------
    # BUILD PDF
    # -----------------------------

    doc.build(
        story,
        onFirstPage=page_decor,
        onLaterPages=page_decor
    )

    return file_path